//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.08 at 05:16:13 PM WET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.exemple.com/wswithspring/soap")
package com.exemple.wswithspring.soap;
